# Generated by Django 4.2.10 on 2024-02-10 23:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("sku", models.TextField()),
                ("name", models.TextField()),
                ("in_stock", models.DecimalField(decimal_places=3, max_digits=100)),
                (
                    "available_stock",
                    models.DecimalField(decimal_places=3, max_digits=100),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboardapi.category",
                    ),
                ),
                ("tags", models.ManyToManyField(to="dashboardapi.tag")),
            ],
        ),
    ]
